import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * AI-powered adaptive DSA learning path backend.
 *
 * NO external dependencies (no Maven/Gradle needed). Compiles with plain javac
 * on Java 11+ (uses java.net.http.HttpClient, added in Java 11).
 *
 * HOW TO RUN
 * ----------
 * 1. Get an API key from https://console.anthropic.com/
 * 2. Set it as an environment variable before starting the server:
 *      Mac/Linux:  export ANTHROPIC_API_KEY=your-key-here
 *      Windows:    set ANTHROPIC_API_KEY=your-key-here
 * 3. Compile:  javac LearningPathServer.java
 * 4. Run:      java LearningPathServer
 * 5. Server starts on http://localhost:8080
 *
 * ENDPOINTS
 * ---------
 * GET  /                                -> health check
 * POST /api/style/detect                -> { "answers": ["visual","written","visual","action"] }
 *                                           returns { "style": "visual" }  (no AI call, just majority vote)
 * POST /api/session/start               -> { "topic": "Arrays", "style": "visual" }
 *                                           returns { sessionId, difficulty, question:{prompt,options,concept} }
 * POST /api/session/answer              -> { "sessionId": "...", "selectedIndex": 2, "timeTakenSeconds": 14 }
 *                                           returns { correct, feedback, explanation, difficulty, done, nextQuestion }
 * GET  /api/session/{id}/dashboard      -> returns { summary, accuracy, difficultyProgression, weeklyPlan, strengths, weaknesses }
 *
 * All AI calls go to Claude (model "claude-sonnet-5"). Difficulty tracking, accuracy stats,
 * and timing are all computed locally in Java -- only question generation, style-adapted
 * explanations, feedback and the weekly plan narrative are generated by the model.
 */
public class LearningPathServer {

    static final int MIN_DIFFICULTY = 1;
    static final int MAX_DIFFICULTY = 5;
    static final int QUESTIONS_PER_SESSION = 8;
    static final String MODEL = "claude-sonnet-5";

    static final HttpClient HTTP_CLIENT = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(20))
            .build();

    static final Map<String, Session> SESSIONS = new ConcurrentHashMap<>();

    public static void main(String[] args) throws IOException {
        if (System.getenv("ANTHROPIC_API_KEY") == null || System.getenv("ANTHROPIC_API_KEY").isBlank()) {
            System.out.println("WARNING: ANTHROPIC_API_KEY is not set. AI calls will fail until you set it.");
        }

        HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
        server.createContext("/", new Router());
        server.setExecutor(null);
        server.start();
        System.out.println("Learning path server running on http://localhost:8080");
    }

    // ----------------------------------------------------------------------------------
    // Routing
    // ----------------------------------------------------------------------------------

    static class Router implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            String path = exchange.getRequestURI().getPath();
            String method = exchange.getRequestMethod();

            // CORS so a simple HTML/JS frontend can call this from a browser
            exchange.getResponseHeaders().add("Access-Control-Allow-Origin", "*");
            exchange.getResponseHeaders().add("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
            exchange.getResponseHeaders().add("Access-Control-Allow-Headers", "Content-Type");
            if (method.equals("OPTIONS")) {
                exchange.sendResponseHeaders(204, -1);
                return;
            }

            try {
                if (path.equals("/") && method.equals("GET")) {
                    sendJson(exchange, 200, Map.of("status", "ok", "message", "Learning path server is running"));
                } else if (path.equals("/api/style/detect") && method.equals("POST")) {
                    handleStyleDetect(exchange);
                } else if (path.equals("/api/session/start") && method.equals("POST")) {
                    handleStart(exchange);
                } else if (path.equals("/api/session/answer") && method.equals("POST")) {
                    handleAnswer(exchange);
                } else if (path.startsWith("/api/session/") && path.endsWith("/dashboard") && method.equals("GET")) {
                    handleDashboard(exchange, path);
                } else {
                    sendJson(exchange, 404, Map.of("error", "Not found: " + method + " " + path));
                }
            } catch (Exception e) {
                e.printStackTrace();
                sendJson(exchange, 500, Map.of("error", e.getMessage() == null ? e.toString() : e.getMessage()));
            }
        }
    }

    // ----------------------------------------------------------------------------------
    // Handlers
    // ----------------------------------------------------------------------------------

    @SuppressWarnings("unchecked")
    static void handleStyleDetect(HttpExchange exchange) throws IOException {
        Map<String, Object> body = (Map<String, Object>) Json.parse(readBody(exchange));
        List<Object> answers = (List<Object>) body.getOrDefault("answers", List.of());

        Map<String, Integer> tally = new HashMap<>();
        for (Object a : answers) {
            String style = String.valueOf(a);
            tally.merge(style, 1, Integer::sum);
        }
        String winner = "written";
        int best = -1;
        for (Map.Entry<String, Integer> e : tally.entrySet()) {
            if (e.getValue() > best) {
                best = e.getValue();
                winner = e.getKey();
            }
        }
        sendJson(exchange, 200, Map.of("style", winner));
    }

    @SuppressWarnings("unchecked")
    static void handleStart(HttpExchange exchange) throws Exception {
        Map<String, Object> body = (Map<String, Object>) Json.parse(readBody(exchange));
        String topic = String.valueOf(body.getOrDefault("topic", "Arrays"));
        String style = String.valueOf(body.getOrDefault("style", "written"));

        Session session = new Session();
        session.id = UUID.randomUUID().toString();
        session.topic = topic;
        session.style = style;
        session.difficulty = MIN_DIFFICULTY;
        SESSIONS.put(session.id, session);

        Map<String, Object> question = generateQuestion(topic, session.difficulty);
        applyQuestionToSession(session, question);

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("sessionId", session.id);
        response.put("difficulty", session.difficulty);
        response.put("question", publicQuestionView(question));
        sendJson(exchange, 200, response);
    }

    @SuppressWarnings("unchecked")
    static void handleAnswer(HttpExchange exchange) throws Exception {
        Map<String, Object> body = (Map<String, Object>) Json.parse(readBody(exchange));
        String sessionId = String.valueOf(body.get("sessionId"));
        int selectedIndex = asInt(body.get("selectedIndex"));
        double timeTaken = body.get("timeTakenSeconds") == null ? 0 : ((Number) body.get("timeTakenSeconds")).doubleValue();

        Session session = SESSIONS.get(sessionId);
        if (session == null) {
            sendJson(exchange, 404, Map.of("error", "Unknown sessionId"));
            return;
        }

        boolean correct = selectedIndex == session.currentCorrectIndex;
        session.difficulty = correct
                ? Math.min(MAX_DIFFICULTY, session.difficulty + 1)
                : Math.max(MIN_DIFFICULTY, session.difficulty - 1);

        HistoryEntry entry = new HistoryEntry();
        entry.concept = session.currentConcept;
        entry.difficulty = session.difficultyBeforeThisAnswer;
        entry.correct = correct;
        entry.timeSeconds = timeTaken;
        session.history.add(entry);
        session.answeredCount++;

        boolean done = session.answeredCount >= QUESTIONS_PER_SESSION;
        session.done = done;

        Map<String, Object> aiResult = generateFeedbackExplanationAndNext(
                session, correct, selectedIndex, done);

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("correct", correct);
        response.put("feedback", aiResult.get("feedback"));
        response.put("explanation", correct ? null : aiResult.get("explanation"));
        response.put("difficulty", session.difficulty);
        response.put("questionsAnswered", session.answeredCount);
        response.put("done", done);

        if (!done) {
            Map<String, Object> nextQuestion = (Map<String, Object>) aiResult.get("nextQuestion");
            applyQuestionToSession(session, nextQuestion);
            response.put("nextQuestion", publicQuestionView(nextQuestion));
        } else {
            response.put("nextQuestion", null);
        }

        sendJson(exchange, 200, response);
    }

    static void handleDashboard(HttpExchange exchange, String path) throws Exception {
        // path looks like /api/session/{id}/dashboard
        String[] parts = path.split("/");
        String sessionId = parts[3];
        Session session = SESSIONS.get(sessionId);
        if (session == null) {
            sendJson(exchange, 404, Map.of("error", "Unknown sessionId"));
            return;
        }

        int totalAnswered = session.history.size();
        long totalCorrect = session.history.stream().filter(h -> h.correct).count();
        double accuracy = totalAnswered == 0 ? 0 : (100.0 * totalCorrect / totalAnswered);

        List<Integer> difficultyProgression = new ArrayList<>();
        double totalTime = 0;
        Map<String, int[]> perConcept = new LinkedHashMap<>(); // concept -> [correct, total]
        for (HistoryEntry h : session.history) {
            difficultyProgression.add(h.difficulty);
            totalTime += h.timeSeconds;
            perConcept.computeIfAbsent(h.concept, k -> new int[2]);
            perConcept.get(h.concept)[1]++;
            if (h.correct) perConcept.get(h.concept)[0]++;
        }
        double avgTime = totalAnswered == 0 ? 0 : totalTime / totalAnswered;

        Map<String, Object> aiSummary = generateDashboardNarrative(session, accuracy, perConcept);

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("topic", session.topic);
        response.put("style", session.style);
        response.put("accuracyPercent", Math.round(accuracy * 10.0) / 10.0);
        response.put("difficultyProgression", difficultyProgression);
        response.put("averageTimeSeconds", Math.round(avgTime * 10.0) / 10.0);
        response.put("questionsAnswered", totalAnswered);
        response.put("summary", aiSummary.get("summary"));
        response.put("weeklyPlan", aiSummary.get("weeklyPlan"));
        response.put("strengths", aiSummary.get("strengths"));
        response.put("weaknesses", aiSummary.get("weaknesses"));

        sendJson(exchange, 200, response);
    }

    // ----------------------------------------------------------------------------------
    // AI prompt calls
    // ----------------------------------------------------------------------------------

    static Map<String, Object> generateQuestion(String topic, int difficulty) throws Exception {
        String system = "You are an adaptive Data Structures & Algorithms tutor for college-level "
                + "computer engineering students. You write one multiple-choice question at a time. "
                + "Respond with ONLY valid JSON, no markdown fences, no extra commentary. "
                + "Format exactly: {\"prompt\":\"question text\",\"options\":[\"opt A\",\"opt B\",\"opt C\",\"opt D\"],"
                + "\"correctIndex\":0,\"concept\":\"short-concept-tag\"}. "
                + "correctIndex is the 0-based index of the correct option in the options array.";

        String user = "Topic: " + topic + ". Difficulty: " + difficulty + " out of 5 "
                + "(1 = basic recall/definitions, 3 = applying the concept to a small example, "
                + "5 = tricky edge cases, complexity analysis, or combining concepts). "
                + "Generate one new multiple-choice question, not previously asked in this conversation.";

        String raw = callClaude(system, user);
        return extractJsonObject(raw);
    }

    @SuppressWarnings("unchecked")
    static Map<String, Object> generateFeedbackExplanationAndNext(
            Session session, boolean correct, int selectedIndex, boolean isLastQuestion) throws Exception {

        String system = "You are an adaptive Data Structures & Algorithms tutor for college-level "
                + "computer engineering students. Respond with ONLY valid JSON, no markdown fences. "
                + "Format exactly: {\"feedback\":\"1-2 encouraging sentences about their answer\","
                + "\"explanation\":\"explanation string, or null if they were correct\","
                + "\"nextQuestion\": {\"prompt\":\"...\",\"options\":[\"...\",\"...\",\"...\",\"...\"],"
                + "\"correctIndex\":0,\"concept\":\"short-concept-tag\"} } . "
                + "If isLastQuestion is true, set nextQuestion to null. "
                + "When writing the explanation, adapt it to the student's preferred learning style: "
                + "'written' = a clear step-by-step text walkthrough; "
                + "'visual' = describe it using a simple structured diagram or ASCII-art layout the student can picture; "
                + "'auditory' = write it as a conversational narration, as if being read aloud; "
                + "'action' = frame it as a hands-on exercise, e.g. 'trace through this yourself step by step: ...'.";

        StringBuilder user = new StringBuilder();
        user.append("Topic: ").append(session.topic).append(". ");
        user.append("Student's preferred learning style: ").append(session.style).append(". ");
        user.append("Concept being tested: ").append(session.currentConcept).append(". ");
        user.append("Question asked: ").append(session.currentPrompt).append(". ");
        user.append("Options were: ").append(session.currentOptions).append(". ");
        user.append("Student selected option index ").append(selectedIndex).append(". ");
        user.append("Correct option index was ").append(session.currentCorrectIndex).append(". ");
        user.append("The student was ").append(correct ? "CORRECT" : "INCORRECT").append(". ");
        user.append("New difficulty level for the next question: ").append(session.difficulty).append(" out of 5. ");
        user.append("isLastQuestion: ").append(isLastQuestion).append(".");

        String raw = callClaude(system, user.toString());
        return extractJsonObject(raw);
    }

    static Map<String, Object> generateDashboardNarrative(
            Session session, double accuracy, Map<String, int[]> perConcept) throws Exception {

        String system = "You are an adaptive Data Structures & Algorithms tutor. Based on a student's "
                + "session performance, write a short summary and a simulated weekly study plan. "
                + "Respond with ONLY valid JSON, no markdown fences. Format exactly: "
                + "{\"summary\":\"2-3 sentence overview of how they did\","
                + "\"weeklyPlan\":[{\"day\":\"Day 1\",\"focus\":\"concept name\",\"activity\":\"what to do\"}, ... 5 to 7 days], "
                + "\"strengths\":[\"short phrase\", ...], \"weaknesses\":[\"short phrase\", ...]}";

        StringBuilder conceptBreakdown = new StringBuilder();
        for (Map.Entry<String, int[]> e : perConcept.entrySet()) {
            conceptBreakdown.append(e.getKey()).append(": ").append(e.getValue()[0])
                    .append("/").append(e.getValue()[1]).append(" correct. ");
        }

        String user = "Topic: " + session.topic + ". Overall accuracy: " + String.format("%.1f", accuracy)
                + "%. Learning style: " + session.style + ". Per-concept results: " + conceptBreakdown
                + " Final difficulty reached: " + session.difficulty + " out of 5. "
                + "Write a plan for the upcoming week that focuses more time on weaker concepts.";

        String raw = callClaude(system, user);
        return extractJsonObject(raw);
    }

    // ----------------------------------------------------------------------------------
    // Anthropic API call
    // ----------------------------------------------------------------------------------

    static String callClaude(String systemPrompt, String userPrompt) throws IOException, InterruptedException {
        String apiKey = System.getenv("ANTHROPIC_API_KEY");
        if (apiKey == null || apiKey.isBlank()) {
            throw new IllegalStateException("ANTHROPIC_API_KEY environment variable is not set.");
        }

        Map<String, Object> messageBody = new LinkedHashMap<>();
        messageBody.put("role", "user");
        messageBody.put("content", userPrompt);

        Map<String, Object> requestBody = new LinkedHashMap<>();
        requestBody.put("model", MODEL);
        requestBody.put("max_tokens", 1024);
        requestBody.put("system", systemPrompt);
        requestBody.put("messages", List.of(messageBody));

        String jsonBody = Json.write(requestBody);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("https://api.anthropic.com/v1/messages"))
                .header("Content-Type", "application/json")
                .header("x-api-key", apiKey)
                .header("anthropic-version", "2023-06-01")
                .timeout(Duration.ofSeconds(60))
                .POST(HttpRequest.BodyPublishers.ofString(jsonBody, StandardCharsets.UTF_8))
                .build();

        HttpResponse<String> response = HTTP_CLIENT.send(request, HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() != 200) {
            throw new IOException("Anthropic API error " + response.statusCode() + ": " + response.body());
        }

        @SuppressWarnings("unchecked")
        Map<String, Object> parsed = (Map<String, Object>) Json.parse(response.body());
        @SuppressWarnings("unchecked")
        List<Object> content = (List<Object>) parsed.get("content");
        @SuppressWarnings("unchecked")
        Map<String, Object> firstBlock = (Map<String, Object>) content.get(0);
        return String.valueOf(firstBlock.get("text"));
    }

    // Claude sometimes wraps JSON in ```json fences or adds stray text -- this strips
    // that and parses just the {...} object.
    @SuppressWarnings("unchecked")
    static Map<String, Object> extractJsonObject(String text) {
        String t = text.trim();
        if (t.startsWith("```")) {
            int firstNewline = t.indexOf('\n');
            if (firstNewline >= 0) t = t.substring(firstNewline + 1);
            int fence = t.lastIndexOf("```");
            if (fence >= 0) t = t.substring(0, fence);
        }
        int start = t.indexOf('{');
        int end = t.lastIndexOf('}');
        String jsonPart = t.substring(start, end + 1);
        return (Map<String, Object>) Json.parse(jsonPart);
    }

    // ----------------------------------------------------------------------------------
    // Session state
    // ----------------------------------------------------------------------------------

    static class Session {
        String id;
        String topic;
        String style;
        int difficulty;
        int difficultyBeforeThisAnswer;
        int answeredCount = 0;
        boolean done = false;

        String currentPrompt;
        List<String> currentOptions;
        int currentCorrectIndex;
        String currentConcept;

        List<HistoryEntry> history = new ArrayList<>();
    }

    static class HistoryEntry {
        String concept;
        int difficulty;
        boolean correct;
        double timeSeconds;
    }

    @SuppressWarnings("unchecked")
    static void applyQuestionToSession(Session session, Map<String, Object> question) {
        session.difficultyBeforeThisAnswer = session.difficulty;
        session.currentPrompt = String.valueOf(question.get("prompt"));
        session.currentOptions = new ArrayList<>();
        for (Object o : (List<Object>) question.get("options")) {
            session.currentOptions.add(String.valueOf(o));
        }
        session.currentCorrectIndex = asInt(question.get("correctIndex"));
        session.currentConcept = String.valueOf(question.get("concept"));
    }

    // Strip the correct answer out before sending a question to the client
    static Map<String, Object> publicQuestionView(Map<String, Object> question) {
        Map<String, Object> view = new LinkedHashMap<>();
        view.put("prompt", question.get("prompt"));
        view.put("options", question.get("options"));
        view.put("concept", question.get("concept"));
        return view;
    }

    // ----------------------------------------------------------------------------------
    // HTTP helpers
    // ----------------------------------------------------------------------------------

    static String readBody(HttpExchange exchange) throws IOException {
        InputStream is = exchange.getRequestBody();
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        byte[] data = new byte[1024];
        int nRead;
        while ((nRead = is.read(data, 0, data.length)) != -1) {
            buffer.write(data, 0, nRead);
        }
        String body = buffer.toString(StandardCharsets.UTF_8);
        return body.isBlank() ? "{}" : body;
    }

    static void sendJson(HttpExchange exchange, int status, Object payload) throws IOException {
        byte[] bytes = Json.write(payload).getBytes(StandardCharsets.UTF_8);
        exchange.getResponseHeaders().add("Content-Type", "application/json");
        exchange.sendResponseHeaders(status, bytes.length);
        try (OutputStream os = exchange.getResponseBody()) {
            os.write(bytes);
        }
    }

    static int asInt(Object o) {
        if (o == null) return 0;
        if (o instanceof Number) return ((Number) o).intValue();
        return Integer.parseInt(String.valueOf(o));
    }

    // ----------------------------------------------------------------------------------
    // Minimal JSON parser/writer (no external libraries needed)
    // ----------------------------------------------------------------------------------

    static class Json {
        static Object parse(String s) {
            return new Parser(s).parseValue();
        }

        static String write(Object o) {
            StringBuilder sb = new StringBuilder();
            writeValue(o, sb);
            return sb.toString();
        }

        private static void writeValue(Object o, StringBuilder sb) {
            if (o == null) {
                sb.append("null");
            } else if (o instanceof String) {
                writeString((String) o, sb);
            } else if (o instanceof Map) {
                sb.append('{');
                boolean first = true;
                for (Map.Entry<?, ?> e : ((Map<?, ?>) o).entrySet()) {
                    if (!first) sb.append(',');
                    first = false;
                    writeString(String.valueOf(e.getKey()), sb);
                    sb.append(':');
                    writeValue(e.getValue(), sb);
                }
                sb.append('}');
            } else if (o instanceof List) {
                sb.append('[');
                boolean first = true;
                for (Object item : (List<?>) o) {
                    if (!first) sb.append(',');
                    first = false;
                    writeValue(item, sb);
                }
                sb.append(']');
            } else if (o instanceof Boolean || o instanceof Number) {
                sb.append(o.toString());
            } else {
                writeString(o.toString(), sb);
            }
        }

        private static void writeString(String s, StringBuilder sb) {
            sb.append('"');
            for (int i = 0; i < s.length(); i++) {
                char c = s.charAt(i);
                switch (c) {
                    case '"': sb.append("\\\""); break;
                    case '\\': sb.append("\\\\"); break;
                    case '\n': sb.append("\\n"); break;
                    case '\r': sb.append("\\r"); break;
                    case '\t': sb.append("\\t"); break;
                    default:
                        if (c < 0x20) sb.append(String.format("\\u%04x", (int) c));
                        else sb.append(c);
                }
            }
            sb.append('"');
        }

        static class Parser {
            final String s;
            int pos = 0;

            Parser(String s) { this.s = s; }

            Object parseValue() {
                skipWs();
                char c = s.charAt(pos);
                if (c == '{') return parseObject();
                if (c == '[') return parseArray();
                if (c == '"') return parseString();
                if (c == 't' || c == 'f') return parseBool();
                if (c == 'n') { pos += 4; return null; }
                return parseNumber();
            }

            Map<String, Object> parseObject() {
                Map<String, Object> map = new LinkedHashMap<>();
                pos++; // {
                skipWs();
                if (s.charAt(pos) == '}') { pos++; return map; }
                while (true) {
                    skipWs();
                    String key = parseString();
                    skipWs();
                    pos++; // :
                    Object val = parseValue();
                    map.put(key, val);
                    skipWs();
                    if (s.charAt(pos) == ',') { pos++; continue; }
                    if (s.charAt(pos) == '}') { pos++; break; }
                }
                return map;
            }

            List<Object> parseArray() {
                List<Object> list = new ArrayList<>();
                pos++; // [
                skipWs();
                if (s.charAt(pos) == ']') { pos++; return list; }
                while (true) {
                    Object val = parseValue();
                    list.add(val);
                    skipWs();
                    if (s.charAt(pos) == ',') { pos++; continue; }
                    if (s.charAt(pos) == ']') { pos++; break; }
                }
                return list;
            }

            String parseString() {
                skipWs();
                pos++; // opening quote
                StringBuilder sb = new StringBuilder();
                while (s.charAt(pos) != '"') {
                    char c = s.charAt(pos);
                    if (c == '\\') {
                        pos++;
                        char e = s.charAt(pos);
                        switch (e) {
                            case '"': sb.append('"'); break;
                            case '\\': sb.append('\\'); break;
                            case '/': sb.append('/'); break;
                            case 'n': sb.append('\n'); break;
                            case 'r': sb.append('\r'); break;
                            case 't': sb.append('\t'); break;
                            case 'b': sb.append('\b'); break;
                            case 'f': sb.append('\f'); break;
                            case 'u':
                                String hex = s.substring(pos + 1, pos + 5);
                                sb.append((char) Integer.parseInt(hex, 16));
                                pos += 4;
                                break;
                            default: sb.append(e);
                        }
                        pos++;
                    } else {
                        sb.append(c);
                        pos++;
                    }
                }
                pos++; // closing quote
                return sb.toString();
            }

            Boolean parseBool() {
                if (s.startsWith("true", pos)) { pos += 4; return Boolean.TRUE; }
                pos += 5;
                return Boolean.FALSE;
            }

            Double parseNumber() {
                int start = pos;
                while (pos < s.length() && "-+.0123456789eE".indexOf(s.charAt(pos)) >= 0) pos++;
                return Double.parseDouble(s.substring(start, pos));
            }

            void skipWs() {
                while (pos < s.length() && Character.isWhitespace(s.charAt(pos))) pos++;
            }
        }
    }
}
